- name: Instalar apache2 en Debian-Ubuntu
  include: insApache.yml
  when: ansible_distribution == "Debian"
- name: Instalar httpd en CentOS
  include: insHttpd.yml
  when: ansible_distribution == "CentOS"
 
- name: Copiar index.html
  template: src=index.html.j2 dest=/var/www/html/index.html